#!/usr/bin/python3

import json
import random
import argparse

from testexecconfig import TestExecConfig
from testexectest import TestExecTest
import pprint

pp = pprint.PrettyPrinter(indent=4)

default_cfg_file = './config.json'

def main( args ):

    cfg_file = default_cfg_file
    if args.cfg:
        cfg_file = args.cfg

    print( cfg_file )
    cfg = TestExecConfig( cfg_file )
    #log = TestExecLogger( cfg.elasticsearch )

    print( 'config file: ', cfg.cfg_file )

    while True:
        # read the config file, it could have changed
        cfg.read()

        # Get a test to run
        test = cfg.get_next_test()


        if test.test_type == 'MTTest':
            print( 'Executing test id:{0} testtype:{1} testname:{2}'.format(
                    test.test_id,
                    test.test_type,
                    test.test_name
                )
            )
            exec_testsimulation( test )

        elif tests.test_type == 'Autodialer':
            print( 'Executing test type Autodialer' )
            exec_autodialer( tests[i] )

        elif tests.test_type == 'LoadTest':
            print( 'Executing test type LoadTest')
            exec_sqm( )

        else:
            print( 'Error: unknown test type' )





def exec_testsimulation( test ):
    return True

def exec_autodialer( test ):
    return True

def exec_sqm( test ):
    return True


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument( '-c', '--cfg', help='Config file, json format' )
    args = parser.parse_args()
    main( args )
