#!/usr/bin/python3

import json
import random
import argparse

from testexec.config import TestExecConfig
from testexec.test import TestExecTest
import pprint

pp = pprint.PrettyPrinter(indent=4)

default_cfg_file = './config.json'

def main( args ):

    cfg_file = default_cfg_file
    if args.cfg:
        cfg_file = args.cfg

    print( cfg_file )
    cfg = TestExecConfig( cfg_file )
    #log = TestExecLogger( cfg.elasticsearch )

    print( 'config file: ', cfg.cfg_file )

    while True:
        # read the config file, it could have changed
        cfg.read()

        # Get a test to run
        test = cfg.get_next_test()

        test.execute()




def exec_testsimulation( test ):
    return True

def exec_autodialer( test ):
    return True

def exec_sqm( test ):
    return True


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument( '-c', '--cfg', help='Config file, json format' )
    args = parser.parse_args()
    main( args )
